### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by Jialiang14** [jiaxiaojunQAQ/LAS-AT#1]
Hello, your work is great and I am very interested in LAS-AT. Thanks for your released code! 
Is there the way of finding the  supplementary material?

**Comment by jiaxiaojunQAQ** [comment]
You can refere to https://openaccess.thecvf.com/content/CVPR2022/html/Jia_LAS-AT_Adversarial_Training_With_Learnable_Attack_Strategy_CVPR_2022_paper.html. The supplementary material has been released.
