### ISSUE TITLE
与训练相关

### ISSUE THREAD

**Issue by IceHowe** [jiaxiaojunQAQ/LAS-AT#2]
你好，整个训练流程是端到端的吗？还是分开训练的？

**Comment by jiaxiaojunQAQ** [comment]
> 你好，整个训练流程是端到端的吗？还是分开训练的？

端到端

**Comment by IceHowe** [comment]
> > 你好，整个训练流程是端到端的吗？还是分开训练的？
> 
> 端到端

就是策略网络和目标网络整体是端到端的吗？我看到好像是先训练一些epoch目标网络，然后训练一个epoch策略网络，然后这样循环

**Comment by jiaxiaojunQAQ** [comment]
> > > 你好，整个训练流程是端到端的吗？还是分开训练的？
> > 
> > 
> > 端到端
> 
> 就是策略网络和目标网络整体是端到端的吗？我看到好像是先训练一些epoch目标网络，然后训练一个epoch策略网络，然后这样循环

他们是交替巡回训练的

**Comment by jiaxiaojunQAQ** [comment]
> > > 你好，整个训练流程是端到端的吗？还是分开训练的？
> > 
> > 
> > 端到端
> 
> 就是策略网络和目标网络整体是端到端的吗？我看到好像是先训练一些epoch目标网络，然后训练一个epoch策略网络，然后这样循环

他们是交替循环训练的
