### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by wang-xm525** [jiaxiaojunQAQ/LAS-AT#3]
你好，我想咨询一下，代码跑完后会自动保存模型吗，我运行完您的代码后，没有找到训练好的模型，还是要我自己用torch.save保存整个模型呢？还是只保存模型参数呢？

**Comment by jiaxiaojunQAQ** [comment]
> 你好，我想咨询一下，代码跑完后会自动保存模型吗，我运行完您的代码后，没有找到训练好的模型，还是要我自己用torch.save保存整个模型呢？还是只保存模型参数呢？

他是保存在这个目录下面  parser.add_argument('--out-dir', default='LAS_AT', type=str, help='Output directory')
 torch.save(target_model_optimizer.state_dict(), os.path.join(out_dir, 'target_model_optimizer.pth'))
 torch.save(policy_optimizer.state_dict(), os.path.join(out_dir, 'policy_model_optimizer.pth'))
一般会新建一个目录，你看看

**Comment by wang-xm525** [comment]
我运行结束后，在out-dir里面是有target和policy的pth文件的，但是 里面就是没有model.pth ，是在test的程序里面使用target和policy的pth文件吗？还是我要重新保存一下整个模型的参数

**Comment by wang-xm525** [comment]
谢谢，了解了
